export type Account = {
  accountId: number;
  firstName: string;
  lastName: string;
  email: string;
  socialClubName: string | null;
  socialClubId: string | null;
  passwordHash: string;
  passwordSalt: string;
  characterCreated: boolean;
  birthDate: string | null;
  origin: string | null;
  customizationJson: string | null;
  adminLevel: number;
  cash: number;
  bankCash: number;
  health: number;
  armor: number;
  dimension: number;
  posX: number;
  posY: number;
  posZ: number;
  rotZ: number;
  isBanned: boolean;
  banReason: string | null;
  banDate: string | null;
  banExpiresAt: string | null;
  banAdminName: string | null;
  banAdminAccountId: number;
};
