ALTER TABLE characters
  ADD COLUMN IF NOT EXISTS experience INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS organization TEXT NOT NULL DEFAULT 'Zivilist',
  ADD COLUMN IF NOT EXISTS organization_rank TEXT NOT NULL DEFAULT 'Keine',
  ADD COLUMN IF NOT EXISTS marital_status TEXT NOT NULL DEFAULT 'single';
